### ISSUE TITLE
update does not seem to trigger a deployment when the Jenkins DeploymentConfig is updated (OpenShift cancels it immediately)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-init-tenant#74]
well the update is fine; it updates the Jenkins DC just fine - but for some reason openshift then decides to ignore that, cancel the deployment so the version 0 keeps running despite version N being more recent. I found I had to manually go into the openshift console and click the `Deploy` button by hand.

I wonder if we need some kinda check to make sure that after the DC has been updated we ensure that openshift properly updated. Maybe we need to detect the `cancelled` state and maybe scale down the DC then try scale it up again? Something like that. Maybe we need to raise this as an openshift bug - it may be our quotas + non-rolling upgrades that cause the issue maybe?

**Comment by kbsingh** [comment]
as a data point, just noticed that the latest updates going out 1.0.154, are restarting all the che instances ( but not the Jenkins ones )

**Comment by jstrachan** [comment]
I just found after updating the jenkins DC by hand to change the docker image version, still no deployment happened. I even tried clicking `Deploy` in the openshift console on the jenkins Deployment page a few times. Still nothing!

Turned out there was an old failed `jenkins-deploy-5` pod. If I deleted that failed pod, then it seemed to kick openshift into life trying to actually deploy it.

So I wonder if init-tenant should try to delete any jenkins deploy pods first? e.g. pods with labels of `openshift.io/deployer-pod-for.name: jenkins-xxxx`. That might help nudge openshift to actually deploy things?

**Comment by jstrachan** [comment]
it does seem that the update tenant seems to re-create the Deployment rather than doing an update/modify. e.g. if I keep doing `oc edit dc jenkins` then each time there's a `jenkins-deploy-1` pod then  `jenkins-deploy-2` .... Each change makes a new version. When update tenant happens it seems to just reset the version back to 1 again that can cause issues if there's an existing deploy pod running (with a higher version) - I think the Deployment is cancelled by openshift as it appears to be going back in time in versions.

So we need to fix up the 'update' logic really to do proper updates of DCs

**Comment by jstrachan** [comment]
I've found to get deploys working I often have to remove the RCs for jenkins-5, jenkins-6 and so forth so that the newly created jenkins-1 can then be re-triggered via `Deploy` on the console

**Comment by joshuawilson** [comment]
Oops, I got distracted and missed pushing the button on the final step. Sorry.
As for the version there is info in the About dialog.

**Comment by aslakknutsen** [comment]
Got a local v working that forks out the che and jenkins parts to oc cli atm. Need a little bit more testing and we can roll it out and give it a spin.
